#!/usr/bin/env python
from __future__ import print_function
import sys

from transfers import get_accession_number

if __name__ == '__main__':
    an = get_accession_number.parse(sys.argv[1])
    print('"' + an + '"') if an else print('None')  # Accession ID must be quoted
    sys.exit(0)
